spring:
  application:
    name: cj-ticketsys
  profiles:
    active: dev
  jackson:
    time-zone: GMT+8

logging:
  config: classpath:logging-config.xml

management:
  endpoint:
    health:
      enabled: true

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml