server:
  port: 8088
  compression:
    enabled: true
    min-response-size: 2048
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
  tomcat:
    uri-encoding: UTF-8

spring:
  datasource:
    name: mydb
    url: jdbc:mysql://172.28.3.45:20010/cj_ticket?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&useSSL=false&allowMultiQueries=true&autoReconnect=true
#    url: jdbc:mysql://172.28.3.45:3306/cj_ticket?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&useSSL=false&allowMultiQueries=true&autoReconnect=true
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    spring.datasource.filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

  redis:
    #      cluster:
    #        nodes: 172.28.2.89:6379
    #        max-redirects: 6
    jedis:
      pool:
        max-idle: 20
        min-idle: 5
        max-wait: -1
        max-active: 30
    password:
    so-timeout: 6000
    timeout: 6000
    max-attempts: 6
#    host: localhost
    host: 172.28.3.45
    port: 6379

  rabbitmq:
#    host: 172.28.3.45
#    username: test
#    password: test
    host: 172.28.3.25
    port: 5672
    username: guest
    password: guest



weedfs:
  host: 172.28.3.25
  port: 9333

b2b:
  ctrip:
    accountId: 7507fc5918b2543e
    secret: f917d8628cc31600ac16ffc5675f6026
    version: 1.0
    aesSecret: 518fa582544823a7
    aesIVSecret: 4d67fa77f78da8fc
    notifyUrl: https://ttdstp.ctrip.com/api/order/notice.do
    momoSoptId: 1
  lvmm:
    momoSoptId: 1
